[package]
name = "arete-codegen"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
convert_case = "0.6.0"
regex = "1.9.4"

[profile.release]
lto = true
strip = true
