[package]
name = "arete_codegen"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
regex = "1.9.4"

arete_codegen_core = { path = "../arete_codegen_core" }
